//
//  main.cpp
//  Problem2
//
//      Each new term in the Fibonacci sequence is generated by adding the
//      previous two terms. By starting with 1 and 2, the first 10 terms will
//      be:
//
//      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//      By considering the terms in the Fibonacci sequence whose values do
//      not exceed four million, find the sum of the even-valued terms.
//
//  Copyright © 2017 castellanese. All rights reserved.
//

#include <iostream>
#include "ProblemUtilities.h"

int main()
{
    size_t const upperLimit{ 4000000 };
    
    size_t f1{ 1 };
    size_t f2{ 1 };
    size_t f3;
    
    size_t sumOfEvenFibs{ 0 };
    
    while (f1 < upperLimit)
    {
        f3 = f1 + f2;
        
        if (num::isEven(f3))
        {
            sumOfEvenFibs += f3;
        }
        
        f1 = f2;
        f2 = f3;
        
    }

    std::cout << "The sum of all even fibonacci numbers under 4000000 is "
    << sumOfEvenFibs
    << std::endl;
    
    return 0;
}
